return {
    cmd = { "taplo", "lsp", "stdio" },
    filetypes = { "toml" },
    root_markers = { ".taplo.toml", "taplo.toml", ".git" },
    settings = {
        evenBetterToml = {
            formatter = {
                alignEntries = true,
                alignComments = true,
                arrayTrailingComma = true,
                arrayAutoExpand = true,
                arrayAutoCollapse = true,
                compactArrays = true,
                compactInlineTables = false,
                inlineTableExpand = true,
                compactEntries = false,
                columnWidth = 80,
                indentTables = false,
                indentEntries = false,
                indentString = "    ",
                trailingNewline = true,
                reorderKeys = false,
                reorderArrays = true,
                reorderInlineTables = false,
                allowedBlankLines = 2,
                crlf = false,
            },
        },
    },
}
