return {
    kind = {
        Text = "",
        Method = "m",
        Function = "",
        Constructor = "",
        Field = "",
        Variable = "",
        Class = "",
        Interface = "",
        Module = "",
        Property = "",
        Unit = "",
        Value = "",
        Enum = "",
        Keyword = "",
        Snippet = "",
        Color = "",
        File = "",
        Reference = "",
        Folder = "",
        EnumMember = "",
        Constant = "",
        Struct = "",
        Event = "",
        Operator = "",
        TypeParameter = "",
    },
    type = {
        Array = " ",
        Number = " ",
        String = " ",
        Boolean = " ",
        Object = " ",
    },
    documents = {
        File = "",
        -- Files = "", -- TODO
        Folder = {
            Folder = "",
            Open = "",
            Empty = "",
            EmptyOpen = "",
            SymLink = "",
            Collapsed = "",
            Expanded = "",
        },
        Indent = {
            Corner = "└",
            Edge = "│",
            Item = "├",
            Bottom = "─",
            None = " ",
        },
        SymLink = "",
        SymLinkArrow = ""
    },
    git = {
        Add = "",
        Mod = "",
        Remove = "",
        Ignore = " ",
        Rename = "",
        Diff = "",
        Repo = "",
        Merge = "",
        Branch = "",
        Commit = "",
    },
    ui = {
        Lock = " ",
        Circle = " ",
        BigCircle = " ",
        BigUnfilledCircle = " ",
        Close = " ",
        NewFile = " ",
        Search = " ",
        Lightbulb = " ",
        Project = " ",
        Dashboard = " ",
        History = " ",
        Comment = " ",
        Bug = " ",
        Code = " ",
        Telescope = " ",
        Gear = " ",
        Package = " ",
        List = " ",
        SignIn = " ",
        SignOut = " ",
        NoteBook = " ",
        Check = " ",
        Fire = " ",
        Note = " ",
        BookMark = "",
        Pencil = " ",
        ChevronRight = "",
        Table = " ",
        Calendar = " ",
        CloudDownload = " ",
        status = {
            Loading = "⟳",
            Failed = "✗",
            Done = "✓",
        },
    },
    diagnostics = {
        Error = "",
        Warning = "",
        Information = "",
        Question = "",
        Hint = "",
    },
    misc = {
        Robot = " ",
        Squirrel = " ",
        Tag = " ",
        Watch = " ",
        OS = {
            LinuxTux = "",
            Apple = "",
            Windows = "",
        },
        keyboard = {
            Space = "󱁐",
            Tab = "󰌒"
        }
    },
}
