#! /bin/bash

# The directory of this repository
CDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
mkdir -p $HOME/.config/

# Download themes for Spicetify
$CDIR/setup-scripts/spicetify_themes.sh

# Symlink files
$CDIR/setup-scripts/stow.sh $CDIR

