#!/usr/bin/env sh

# The directory of this repository
current_directory=$(CDPATH= cd -- "$( dirname -- "$0")" && pwd)

# Install packages required to run this script
required_packages="${CDIR}/etc/required.txt"
if [ -s "$required_packages" ]; then
    sudo pacman -S --needed - < "$required_packages"
fi

# Make sure XDG Base Directory Specification is used
XDG_CONFIG_HOME="${HOME}/.config"
XDG_CACHE_HOME="${HOME}/.cache"
XDG_DATA_HOME="${HOME}/.local/share"
XDG_STATE_HOME="${HOME}/.local/state"

# Create important directories
mkdir -p "${XDG_CONFIG_HOME}"
mkdir -p "${XDG_CACHE_HOME}"
mkdir -p "${XDG_DATA_HOME}"
mkdir -p "${XDG_STATE_HOME}"

mkdir -p "${HOME}/.local/bin"

# Download paru (https://aur.archlinux.org/packages/paru) so packages from the AUR can be installed.
# $current_directory/setup-scripts/paru.sh

# Download themes for Spicetify
# TODO: add as submodule
# $current_directory/setup-scripts/spicetify_themes.sh

# Symlink files
# $current_directory/setup-scripts/stow.sh $current_directory

# sudo ln -sf $current_directory/etc/unlock-conservation-mode.service /etc/systemd/system/
# sudo systemctl enable unlock-conservation-mode

