#!/bin/bash

# The directory of this repository
CDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Make sure some directories exist before symlinking
$CDIR/setup-scripts/ensure-dirs.sh

# Download paru (https://aur.archlinux.org/packages/paru) so packages from the AUR can be installed.
$CDIR/setup-scripts/paru.sh

# Download themes for Spicetify
# TODO: add as submodule
$CDIR/setup-scripts/spicetify_themes.sh

# Symlink files
$CDIR/setup-scripts/stow.sh $CDIR

sudo ln -sf $CDIR/etc/unlock-conservation-mode.service /etc/systemd/system/
sudo systemctl enable unlock-conservation-mode

