resolver: lts-20.16

packages:
  - .
  - ./xmobar

flags:
  xmobar:
    # with_dbus: true
    with_threaded: true
    with_xrender: true
    with_xpm: true
    with_alsa: true
    # all_extensions: true

extra-deps:
  - netlink-1.1.1.0
  - X11-xft-0.3.4
