require "config.options"
require "config.keymaps"
require "config.plugins"
require "config.colorscheme"
require "config.cmp"
require "config.lsp"
require "config.presence"
require "config.telescope"
-- require "config.colorizer"
require "config.treesitter"
require "config.autopairs"

